<a href="https://colab.research.google.com/github/krishjoshi7/ml/blob/main/ANN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Importing dependencies

In [1]:
import pandas as pd
import numpy as np
import tensorflow as tf


In [2]:
tf.__version__

'2.13.0'

###Data preprocessing

importing the dataset

In [3]:
dataset = pd.read_csv('/content/Churn_Modelling.csv')

In [5]:
dataset.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

###seperating the dependent and independent variable

In [6]:
X = dataset.iloc[:, 3:-1].values
y = dataset.iloc[:, -1].values

In [7]:
print(X)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


In [8]:
print(y)

[1 0 1 ... 1 1 0]


###Encoding catagorical data

label encoding "Gender" column

In [15]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:, 2] = le.fit_transform(X[:, 2])

In [16]:
print(X)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 0 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


###One Hot encoding

In [17]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [18]:
print(X)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


###splitting the data into training and testing

In [19]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

###Feature Scaling

In [20]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

# Building ANN Model

###Initializing the Ann

In [22]:
ann = tf.keras.models.Sequential()

### Adding the input layer first hidden layer

In [23]:
ann.add(tf.keras.layers.Dense(units=6, activation = 'relu'))

### Adding the second hidden layer

In [25]:
ann.add(tf.keras.layers.Dense(units=6, activation ='relu'))

### Adding output layer

In [26]:
ann.add(tf.keras.layers.Dense(units=1, activation ='sigmoid'))

# Training the ANN

### compiling the ANN

In [32]:
ann.compile(optimizer= 'adam', loss='binary_crossentropy', metrics = ['accuracy'])

###Training the ANN on Training Set

In [36]:
ann.fit(X_train, y_train, batch_size=32, epochs = 108)

Epoch 1/108
250/250 [==============================] - 3s 4ms/step - loss: 0.5355 - accuracy: 0.7960
Epoch 2/108
250/250 [==============================] - 1s 3ms/step - loss: 0.4653 - accuracy: 0.7960
Epoch 3/108
250/250 [==============================] - 1s 3ms/step - loss: 0.4463 - accuracy: 0.7975
Epoch 4/108
250/250 [==============================] - 1s 2ms/step - loss: 0.4378 - accuracy: 0.8083
Epoch 5/108
250/250 [==============================] - 1s 2ms/step - loss: 0.4318 - accuracy: 0.8161
Epoch 6/108
250/250 [==============================] - 1s 3ms/step - loss: 0.4259 - accuracy: 0.8227
Epoch 7/108
250/250 [==============================] - 1s 3ms/step - loss: 0.4210 - accuracy: 0.8273
Epoch 8/108
250/250 [==============================] - 1s 2ms/step - loss: 0.4172 - accuracy: 0.8306
Epoch 9/108
250/250 [==============================] - 1s 3ms/step - loss: 0.4146 - accuracy: 0.8300
Epoch 10/108
250/250 [==============================] - 1s 3ms/step - loss: 0.4123 - accura

# Making the prediction and evaluating the model

### predicting the result of single observation

In [37]:
print(ann.predict(sc.transform([[1, 0, 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]])) > 0.5)

1/1 [==============================] - 0s 114ms/step
[[False]]


Therefore, our ANN model predicts that this customer stays in the bank!

**Important note 1:** Notice that the values of the features were all input in a double pair of square brackets. That's because the "predict" method always expects a 2D array as the format of its inputs. And putting our values into a double pair of square brackets makes the input exactly a 2D array.

**Important note 2:** Notice also that the "France" country was not input as a string in the last column but as "1, 0, 0" in the first three columns. That's because of course the predict method expects the one-hot-encoded values of the state, and as we see in the first row of the matrix of features X, "France" was encoded as "1, 0, 0". And be careful to include these values in the first three columns, because the dummy variables are always created in the first columns.

### Predicting the Test set results

In [38]:
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

63/63 [==============================] - 0s 1ms/step
[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


### Making Confusion Matrix

In [39]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[1523   72]
 [ 204  201]]


0.862